apiVersion: apps/v1
kind: Deployment
metadata:
 name: flask-microservice
spec:
  replicas: 2
  selector:
   matchLabels:
    app: flask-microservice
  template:
   metadata:
    labels:
     app: flask-microservice
   spec:
    containers:
    - name: flask-microservice
      image: mo4222/todo-app:latest
      ports:
      - containerPort: 5000