apiVersion: apps/v1
kind: Deployment
metadata:
 name: flask-microservice
spec:
  replicas: 3
  selector:
   matchLabels:
    app: flask-microservice
  template:
   metadata:
    labels:
     app: flask-microservice
   spec:
    containers:
    - name: flask-microservice
      image: mo4222/solar-system:latest
      ports:
      - containerPort: 5000
      env:
      - name: MYSQL_DATABASE_HOST
        value: "mysql-service"
      - name: MYSQL_DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: username
      - name: MYSQL_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: password
      - name: MYSQL_DATABASE_DB
        value: "employee_db"