apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-microservice
  labels:
    app: python-microservice
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: python-microservice
  template:
    metadata:
      labels:
        app: python-microservice
    spec:
      containers:
      - name: python-microservice
        image: ${DOCKER_IMAGE}  # Will be replaced by GitHub Actions
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: MYSQL_DATABASE_HOST
          value: "${MYSQL_HOST}"  # Will be replaced by GitHub Actions
        - name: MYSQL_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE_DB
          value: "${MYSQL_DATABASE}"  # Will be replaced by GitHub Actions
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
        startupProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 8
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 8
          failureThreshold: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false