apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  # These will be replaced by GitHub Actions pipeline
  username: "${MYSQL_USERNAME}"
  password: "${MYSQL_PASSWORD}"