apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # These are base64 encoded values - replace with your actual encoded values
  # To encode: echo -n "your_value" | base64
  username: ZGJfdXNlcg==        # base64 encoded 'db_user'
  password: UGFzc3cwcmQ=        # base64 encoded 'Passw0rd'
  root-password: UGFzc3cwcmQ=   # base64 encoded 'Passw0rd'
  