apiVersion: v1
kind: Service
metadata:
  name: flask-microservice-service
  namespace: default
  labels:
    app: flask-microservice
spec:
  selector:
    app: flask-microservice
  ports:
    - name: http               
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
