apiVersion: v1
kind: Service
metadata:
  name: python-microservice-service
  labels:
    app: python-microservice
spec:
  selector:
    app: python-microservice  # Fixed: matches deployment labels
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000  # Fixed: Flask app runs on 5000
    name: http
  type: LoadBalancer