apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-microservice
  namespace: monitoring
  labels:
    release: kube-prometheus-stack   # must match your Prometheus release
spec:
  selector:
    matchLabels:
      app: flask-microservice        # must match your Service's label
  namespaceSelector:
    matchNames:
      - default                      # where your app Service lives
  endpoints:
    - port: http                     # must match the name of the port in your Service
      path: /metrics
      interval: 15s
      scheme: http
