apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-microservice-monitor
  namespace: monitoring
  labels:
    app: python-microservice
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: python-microservice  # Fixed: matches service labels
  namespaceSelector:
    matchNames: ["default"]
  endpoints:
  - port: http  # Matches service port name
    path: /metrics  # Note: You'll need to add Prometheus metrics to Flask app
    interval: 15s
    scheme: http
    honorLabels: true