apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
 name: flask-microservice
 namespace: monitoring
 labels:
  release: kube-prometheus-stack
spec:
 selector:
  matchLabels:
   app: flask-microservice
 namespaceSelector:
  matchNames: ["default"]
 endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scheme: http
  - port: http
    path: /health
    interval: 30s
    scheme: http